-- 1. Create Books Table
create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  category text not null,
  description text not null,
  price numeric not null,
  stock bigint not null default 0,
  published_year bigint not null,
  cover_gradient text not null,
  rating numeric not null default 4.0
);

-- 2. Create User Profiles Table (role management)
create table if not exists public.profiles (
  id uuid primary key references auth.users on delete cascade,
  role text not null default 'customer' check (role in ('customer', 'admin'))
);

-- 3. Create Orders Table
create table if not exists public.orders (
  id uuid default gen_random_uuid() primary key,
  created_at timestamptz default now() not null,
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  delivery_address text not null,
  order_notes text,
  payment_method text not null,
  payment_details jsonb not null default '{}'::jsonb,
  total_amount numeric not null,
  items jsonb not null default '[]'::jsonb
);

-- 4. Enable Row Level Security (RLS) bypass for quick development,
-- or configure public access. For client-side quick integrations, 
-- we will disable RLS on public tables so client keys can read/write.
alter table public.books disable row level security;
alter table public.profiles disable row level security;
alter table public.orders disable row level security;

-- 5. Seed default book catalog
insert into public.books (title, author, category, description, price, stock, published_year, cover_gradient, rating) values
('The Midnight Library', 'Matt Haig', 'fiction', 'Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.', 14.99, 12, 2020, 'linear-gradient(135deg, #6366f1, #a855f7)', 4.6),
('Atomic Habits', 'James Clear', 'self-help', 'No matter your goals, Atomic Habits offers a proven framework for improving—every day. James Clear, one of the world''s leading experts on habit formation, reveals practical strategies.', 16.20, 8, 2018, 'linear-gradient(135deg, #f59e0b, #e11d48)', 4.9),
('Clean Code', 'Robert C. Martin', 'tech', 'Even bad code can run. But if code isn''t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code.', 32.50, 15, 2008, 'linear-gradient(135deg, #06b6d4, #3b82f6)', 4.8),
('The Intelligent Investor', 'Benjamin Graham', 'business', 'The greatest investment advisor of the twentieth century, Benjamin Graham, taught and inspired people worldwide. Graham''s philosophy of ''value investing'' has shielded investors from substantial error.', 22.99, 5, 1949, 'linear-gradient(135deg, #10b981, #059669)', 4.7),
('Klara and the Sun', 'Kazuo Ishiguro', 'fiction', 'A magnificent new novel by the Nobel laureate Kazuo Ishiguro—his first since winning the Nobel Prize in Literature—that offers a thrilling look at our changing world through the eyes of an unforgettable narrator.', 15.99, 0, 2021, 'linear-gradient(135deg, #ec4899, #f43f5e)', 4.2),
('Designing Data-Intensive Applications', 'Martin Kleppmann', 'tech', 'Want to understand how to design and build scalable, reliable, and maintainable systems? Learn how to navigate the diverse landscape of databases, queues, and stream processing.', 38.95, 6, 2017, 'linear-gradient(135deg, #2563eb, #7c3aed)', 4.9),
('Thinking, Fast and Slow', 'Daniel Kahneman', 'self-help', 'Daniel Kahneman, the renowned psychologist and winner of the Nobel Prize in Economics, takes us on a groundbreaking tour of the mind and explains the two systems that drive the way we think.', 18.00, 10, 2011, 'linear-gradient(135deg, #f97316, #ea580c)', 4.5),
('Zero to One', 'Peter Thiel', 'business', 'If you want to build a better future, you must believe in secrets. The great secret of our time is that there are still uncharted frontiers to explore and new inventions to create.', 14.50, 4, 2014, 'linear-gradient(135deg, #0d9488, #0ea5e9)', 4.4);

-- 6. Setup Auth Profile Trigger
-- Automatically create a profile entry when a user registers via Supabase Auth
create or replace function public.handle_new_user()
returns trigger as $$
begin
  -- The first user to sign up will be the admin (optional helper), 
  -- otherwise all new signups default to 'customer'.
  if not exists (select 1 from public.profiles) then
    insert into public.profiles (id, role)
    values (new.id, 'admin');
  else
    insert into public.profiles (id, role)
    values (new.id, 'customer');
  end if;
  return new;
end;
$$ language plpgsql security definer;

-- Trigger definition
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
